# Generated by Django 4.2 on 2023-04-13 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is still active?')),
                ('members', models.ManyToManyField(related_name='teams', to='employees.employee', verbose_name='Members')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Project title')),
                ('description', models.TextField(verbose_name='Project description')),
                ('client', models.CharField(max_length=255, verbose_name='Client')),
                ('deadline', models.DateField(default=django.utils.timezone.now, verbose_name='Deadline')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is still active?')),
                ('team', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='projects.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
