# Generated by Django 4.2 on 2023-04-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='job_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
